### ISSUE TITLE
Wrapper on iOS doesn't allow payment with Apple Pay through Stripe

### ISSUE THREAD

**Issue by gianni-gulino-eleva** [vuestorefront/vue-storefront#6712] opened 2022-05-02 13:02 UTC
### What is your question / Please describe your issue

Hi everyone, I have a problem with Stripe integration on VSF.
I have integrated the payment via Stripe on a VSF project, the payment via Google Pay and Apple Pay works fine.

The problem arises when I go to generate the application for iOS via wrapper using XCode: in this case, the button for payment with Apple Pay does not appear.

I assume the problem may be related to the wrapper running on a browser other than Safari.

Any ideas on how to fix this?

Thanks in advance

### What version of Vue Storefront are you using?

1.12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment] 2022-05-05 13:12
Duplicate of https://github.com/vuestorefront/vue-storefront/discussions/6713

**Closed by filipsobol** 2022-05-05 13:12 UTC
