### ISSUE TITLE
Separate building stage from yarn:start

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#3543] opened 2019-09-13 11:04 UTC
## Current behavior
PM2 requires ts-node instead of running purely on the built code from `dist`

## Expected behavior
I can build the project with dev dependencies, install prod dependencies only, move the full artifact to the prod server and run the app without any building

## Steps to reproduce the issue
See how ecosystem.json and package.json are configured

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

I marked it as to develop because it should be fixed in 2.0 rather than 1.11 due to major potentially breaking changes

**Comment by pkarw** [comment] 2019-09-13 11:10
It will be closed by #3539

**Comment by pkarw** [comment] 2019-09-27 22:23
it's not a bug by the way - so I changed the type

**Closed** 2021-08-20 02:16 UTC
Labels: feature request, P1: Urgent, 3: Medium complexity, VSF1
